// Generates migrations/0002_seed.sql from the default content and a hashed
// initial admin password. Reuses the Worker's auth.js (WebCrypto works in Node 22).
//
// Configure the first login with env vars (optional):
//   ADMIN_EMAIL=you@clinic.ca ADMIN_PASSWORD='a good password' npm run gen:seed
//
// Re-running is safe: content uses INSERT OR IGNORE, so client edits are preserved,
// and the admin row is only inserted if it doesn't already exist.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { DEFAULT_CONTENT } from "../src/lib/defaults.js";
import { hashPassword } from "../src/lib/auth.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

const ADMIN_EMAIL = (process.env.ADMIN_EMAIL || "admin@cedarhealthcare.ca").trim().toLowerCase();
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || "ChangeMe-Cedar2026!";

const sqlStr = (s) => "'" + String(s).replace(/'/g, "''") + "'";

const lines = [
  "-- Generated by scripts/gen-seed.mjs — do not edit by hand.",
  "-- Seeds default site content and the initial admin login.",
  ""
];

for (const [section, value] of Object.entries(DEFAULT_CONTENT)) {
  lines.push(
    `INSERT OR IGNORE INTO content (section, data) VALUES (${sqlStr(section)}, ${sqlStr(JSON.stringify(value))});`
  );
}

lines.push("");
const hash = await hashPassword(ADMIN_PASSWORD);
lines.push(
  `INSERT OR IGNORE INTO admins (email, password_hash) VALUES (${sqlStr(ADMIN_EMAIL)}, ${sqlStr(hash)});`
);
lines.push("");

const outPath = join(__dirname, "..", "migrations", "0002_seed.sql");
writeFileSync(outPath, lines.join("\n"), "utf8");

console.log("Wrote", outPath);
console.log("-------------------------------------------");
console.log("Initial admin login:");
console.log("  email:   ", ADMIN_EMAIL);
console.log("  password:", ADMIN_PASSWORD);
console.log("  (change it after first sign-in, in Admin → Account)");
console.log("-------------------------------------------");
